import slides from '@/lib/slides.json';
import { SlideCopy } from '@/components/deck/slide-copy';
import Image from 'next/image';
export default function Print() {
  return <main className="print-deck">{slides.map(slide => <article className={`print-slide ${slide.index === '01' || slide.index === '16' ? 'bookend' : ''}`} key={slide.id}>
    <div className="print-copy"><div className="eyebrow">{slide.label}</div><h1>{slide.heading}</h1><SlideCopy slide={slide} /></div>
    <div className="print-art">{slide.index === '10' ? <Image src="/media/02-perfume-poster.jpg" alt="Still from the floating perfume bottle video" width={1920} height={1080} className="h-full w-full object-contain" /> : slide.index === '09' ? <Image src="/media/09-dom-perignon.png" alt="Dom Perignon bottle above Earth" width={1665} height={944} className="h-full w-full object-contain" /> : slide.index === '08' ? <Image src="/media/08-watch.png" alt="Watch with an orbital scene on its dial" width={2048} height={1152} className="h-full w-full object-contain" /> : slide.index === '07' ? <Image src="/media/07-lvmh-value.png" alt="LVMH Maison-branded astronaut concept" width={1678} height={944} className="h-full w-full object-contain" /> : slide.index === '06' ? <Image src="/media/02-satellite-poster.jpg" alt="Still from the satellite platform video" width={1280} height={720} className="h-full w-full object-contain" /> : slide.index === '05' ? <Image src="/media/05-cosmos.png" alt="Cosmos orbital diagrams" width={2048} height={1152} className="h-full w-full object-contain" /> : slide.index === '04' ? <Image src="/media/04-lv-poster.jpg" alt="Still from the supplied Louis Vuitton video" width={1280} height={720} className="h-full w-full object-contain" /> : slide.index === '03' ? <Image src="/media/03-ardbeg-research.jpg" alt="Ardbeg research with laboratory equipment and a whisky bottle" width={1280} height={848} className="h-full w-full object-contain" /> : slide.index === '01' || slide.index === '02' ? <Image src={slide.index === '01' ? '/media/01-opening-poster.jpg' : '/media/02-sneaker-poster.jpg'} alt={slide.index === '01' ? 'Still from the Project Rhapsody sizzle film' : 'Still from the floating sneaker video'} width={1920} height={1080} className="h-full w-full object-cover" /> : <span>FPO {slide.index}<br />{slide.label}</span>}</div>
    <footer><span>Project Rhapsody / LVMH Partnership</span><span>Confidential</span><span>{slide.index} / 16</span></footer>
  </article>)}</main>;
}
